name: Publish documentation

on:
  workflow_dispatch:
    inputs:
      documentation_tag:
        type: string
        required: false
        default: "latest"
        description: "Label of the documentation"

  workflow_call:
    inputs:
      documentation_tag:
        type: string
        required: true
        default: "latest"

jobs:
  Publish_Documentation:
    env:
      ARCHIVE: "sidewalk_${{inputs.documentation_tag}}.zip"

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nrfconnect/sdk-sidewalk:main
      options: --cpus 2
    defaults:
      run:
        shell: nrfutil toolchain-manager launch --install-dir /root/ncs bash -- {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: sidewalk

      - name: Build documentation
        run: |
          cd sidewalk/doc
          ./build_local.sh

          cp custom.properties build/html
          sed -i 's/__VERSION__/'"${{inputs.documentation_tag}}"'/g' build/html/custom.properties

          cp tags.yml build/html
          sed -i 's/__VERSION__/'"${{inputs.documentation_tag}}"'/g' build/html/tags.yml

          cd build/html
          zip -rq "${ARCHIVE}" .
          mv "${ARCHIVE}" /workdir

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: |
            /workdir/${ARCHIVE}

      - name: Prepare access key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan upload-v1.zoominsoftware.io >> ~/.ssh/known_hosts
          echo "${{ secrets.NCS_ZOOMIN_KEY }}" | base64 -d > zoomin_key
          chmod 600 zoomin_key

      - name: Publish documentation
        run: |
          sftp -v -i zoomin_key nordic@upload-v1.zoominsoftware.io <<EOF
            cd nordic-be-dev.zoominsoftware.io/sphinx-html/incoming
            put /workdir/${ARCHIVE}
            quit
          EOF
